# (C) Copyright 2019- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

from itertools import chain

from .missing import convert_missing_scalar

SKIP_KEYS = {
    "unexpandedDescriptors",
    "shortDelayedDescriptorReplicationFactor",
    "delayedDescriptorReplicationFactor",
    "extendedDelayedDescriptorReplicationFactor",
    "delayedDescriptorAndDataRepetitionFactor",
    "extendedDelayedDescriptorAndDataRepetitionFactorassociatedFieldSignificance",
    "dataPresentIndicator",
    "operator",
}

"""
For messages with uncompressed subsets consider this:

- for each data key we have a single value
- there is no way to identify the subset from the key
- we cannot directly iterate over a given subset
- if we iterate over the keys a new subset is indicated by the
  appearance of the "subsetNumber" key, which contains the same array
  of values each time (the subset index for all the subsets). This key is
  generated by ecCodes and does not contain any ranking so its name is
  always "subsetNumber".

"""


class UncompressedBufrKey:
    def __init__(self, key, name: str, rank):
        """Create a key from its already decoded components.

        Parameters
        ----------
        key: str
            The original BUFR key as it appears in the message, e.g. "#2#airTemperature".
        name: str
            The key name without the rank, e.g. "airTemperature".
        rank: int
            The rank of the key within the message. 0 means the key has no rank.
        """
        self.key = key
        self.name = name
        self.rank = rank
        self.ranked_name = f"#{rank}#{name}" if rank > 0 else name

    @classmethod
    def from_key(cls, key: str) -> "UncompressedBufrKey":
        """Build a key by parsing the rank out of a BUFR key.

        Parameters
        ----------
        key: str
            The BUFR key, either ranked ("#2#airTemperature") or unranked ("airTemperature").

        Returns
        -------
        UncompressedBufrKey
            The parsed key. When the rank cannot be determined it defaults to 1.
        """
        rank_text, sep, name = key.rpartition("#")
        try:
            if sep == "#":
                rank = int(rank_text[1:])
            else:
                rank = 1
        except Exception:
            rank = 1

        return cls(key, name, rank)

    def rerank(self, base_rank: int) -> str:
        """Rename the key so that its rank is relative to the given base rank.

        Within a message the ranks are continuous across the whole message, so in the
        second and subsequent subsets they do not start at 1. This method maps the
        message-wide rank onto the subset-local rank.

        Parameters
        ----------
        base_rank: int
            The rank the key had at its first occurrence in the current subset.

        Returns
        -------
        str
            The re-ranked key name, e.g. "#1#airTemperature". When the relative rank is
            not positive the original ranked name is returned unchanged.
        """
        rel_rank = self.rank - base_rank + 1
        if rel_rank > 0:
            return f"#{rel_rank}#{self.name}"
        else:
            return self.ranked_name


class RefRank:
    def __init__(self, value=-1):
        """Create a tracker for the reference rank of a given key name.

        Parameters
        ----------
        value: int, optional
            The initial reference rank. The default (-1) means that the reference rank
            is not set yet.
        """
        self.value = value

    def reset(self):
        """Clear the reference rank. Must be called when a new subset starts."""
        self.value = -1

    def set(self, value: int):
        """Store the reference rank if it is not set yet.

        Only the first call after creation or :meth:`reset` has an effect, so the
        reference rank is always the rank of the first occurrence of the key within
        the current subset.

        Parameters
        ----------
        value: int
            The candidate reference rank.
        """
        if self.value == -1:
            self.value = value


class UncompressedExtractor:
    def __init__(self, base_result, message, subset_count, data_columns, data_filters, add_filters):
        """Create an extractor collecting a given set of data columns from each subset.

        Parameters
        ----------
        base_result: dict
            The values already collected from the header. Each generated result starts
            as a copy of it.
        message: MessageWrapper
            The message to extract the data section from.
        subset_count: int
            The number of subsets in the message.
        data_columns: dict
            The data columns to extract, keyed by column name.
        data_filters: dict
            The filters to apply to the data section, keyed by filter key.
        add_filters: bool
            If True the values of the matched simple filters are added to the result.
        """
        self.message = message
        self.data_columns = data_columns
        self.subset_count = subset_count
        self.base_result = base_result
        self.data_filters = data_filters
        self.add_filters = add_filters

        # create set of all data keys to extract from a given subset, contains re-ranked keys
        subset_keys = set()
        ref_rank = {}

        # get filter keys containing a rank or computed key
        simple_filters = {f.key: f for f in data_filters.values() if not f.column.multi}

        # get data column names containing a rank or computed key
        simple_columns = {c.name: c for c in data_columns.values() if not c.multi}

        # setup rank tracker for the keys that need to be collected
        # subset keys contain the ranked keys to collect
        for col in chain([f.column for f in simple_filters.values()], simple_columns.values()):
            for key in col.keys:
                if key not in subset_keys:
                    b = UncompressedBufrKey.from_key(key)
                    subset_keys.add(b.ranked_name)
                    if b.name not in ref_rank:
                        ref_rank[b.name] = RefRank()

        self.subset_keys = subset_keys
        self.ref_rank = ref_rank

        # the multi-rank keys are treated separately
        self.multi_rank_filter_keys = [f.name for f in self.data_filters.values() if f.column.multi]
        self.multi_rank_data_keys = [c.name for c in self.data_columns.values() if c.multi]

    def extract(self):
        """Generate a result for each subset in the message.

        The keys are iterated in message order and a new subset is detected by the
        appearance of the "subsetNumber" key.

        Yields
        ------
        dict
            The result for a subset. Subsets rejected by the filters are skipped.
        """
        subset_values = dict()
        multi_rank_data_values = {x: [] for x in self.multi_rank_data_keys}
        multi_rank_filter_values = {x: [] for x in self.multi_rank_filter_keys}

        subset = 0
        for key in self.message:
            # only the data section is processed here

            # start new subset
            if key == "subsetNumber":
                if subset >= 1:
                    current_result = self.generate_subset_result(
                        subset_values, multi_rank_filter_values, multi_rank_data_values
                    )

                    if current_result:
                        yield current_result

                subset += 1
                subset_values.clear()
                multi_rank_filter_values = {x: [] for x in self.multi_rank_filter_keys}
                multi_rank_data_values = {x: [] for x in self.multi_rank_data_keys}

                for x in self.ref_rank.values():
                    x.reset()

            elif subset >= 1:
                self.process_key(key, subset_values, multi_rank_filter_values, multi_rank_data_values)

        # last subset
        current_result = self.generate_subset_result(subset_values, multi_rank_filter_values, multi_rank_data_values)
        if current_result:
            yield current_result

    def process_key(self, key, subset_values, multi_rank_filter_values, multi_rank_data_values):
        """Collect the value of a single data key into the buffers of the current subset.

        Keys that are neither required by a column nor by a filter are ignored.

        Parameters
        ----------
        key: str
            The BUFR key to process.
        subset_values: dict
            Buffer of the single-rank values, keyed by the re-ranked key name. Updated
            in place.
        multi_rank_filter_values: dict
            Buffer of the values of the multi-rank filter keys, keyed by key name.
            Updated in place.
        multi_rank_data_values: dict
            Buffer of the values of the multi-rank data columns, keyed by key name.
            Updated in place.
        """

        def _get_value(key):
            return convert_missing_scalar(self.message.get(key))

        b = UncompressedBufrKey.from_key(key)
        if b.name in self.ref_rank:
            self.ref_rank[b.name].set(b.rank)
            reranked_key = b.rerank(self.ref_rank[b.name].value)
            if reranked_key in self.subset_keys:
                subset_values[reranked_key] = _get_value(key)
        else:
            if b.name in self.multi_rank_data_keys:
                multi_rank_data_values[b.name].append(_get_value(key))
            if b.name in self.multi_rank_filter_keys:
                multi_rank_filter_values[b.name].append(_get_value(key))

    def generate_subset_result(self, subset_values, multi_rank_filter_values, multi_rank_data_values):
        """Apply the filters to the collected values and build the result of a subset.

        Parameters
        ----------
        subset_values: dict
            The single-rank values collected for the subset, keyed by the re-ranked key
            name.
        multi_rank_filter_values: dict
            The values of the multi-rank filter keys collected for the subset, keyed by
            key name.
        multi_rank_data_values: dict
            The values of the multi-rank data columns collected for the subset, keyed by
            key name.

        Returns
        -------
        dict or None
            The result built from :obj:`base_result` and the requested data columns, or
            None when the subset does not match the filters.
        """

        def _get_value_subset(key):
            if key in multi_rank_filter_values:
                return multi_rank_filter_values.get(key)
            elif key in multi_rank_data_values:
                return multi_rank_data_values.get(key)
            else:
                return subset_values.get(key)

        current_result = dict(self.base_result)

        # generate result for previous subset
        matched = True
        matched_keys = {}
        for f in self.data_filters.values():
            match, value = f.match_accessor(_get_value_subset)
            if not match:
                matched = False
                break

            if self.add_filters and not f.column.multi:
                matched_keys[f.key] = value

        if matched:
            for key, c in self.data_columns.items():
                # LOG.debug(f"getting data column key: {key}")
                if not c.multi:
                    if key not in current_result:
                        v = c.get_value(_get_value_subset)
                        current_result[key] = v
                else:
                    for k, v in c.get_ranked_items(_get_value_subset):
                        current_result[k] = v

            if matched_keys:
                current_result.update(matched_keys)

            if current_result:
                # print("yielding:", current_result)
                return dict(current_result)

        return None


class UncompressedExtractorAll:
    def __init__(
        self, base_result, message, subset_count, add_data, data_filters, add_filters, data_required_columns_keys
    ):
        """Create an extractor collecting the whole data section of each subset.

        Parameters
        ----------
        base_result: dict
            The values already collected from the header. Each generated result starts
            as a copy of it.
        message: MessageWrapper
            The message to extract the data section from.
        subset_count: int
            The number of subsets in the message.
        add_data: bool
            If True all the data keys are added to the result. If False only the keys
            needed by the filters and the required columns are collected.
        data_filters: dict
            The filters to apply to the data section, keyed by filter key.
        add_filters: bool
            If True the matched simple filter keys are tracked separately. When
            :obj:`add_data` is False they are then removed from the collected values.
        data_required_columns_keys: list or None
            The data keys of the required columns. Only used when :obj:`add_data` is
            False.
        """
        self.message = message
        self.subset_count = subset_count
        self.base_result = base_result
        self.add_data = add_data
        self.data_filters = data_filters
        self.add_filters = add_filters
        self.data_required_columns_keys = data_required_columns_keys

        # create set of all data keys to extract from a given subset
        # contains re-ranked keys
        ref_rank = {}
        simple_filters = {f.key: f for f in self.data_filters.values() if not f.column.multi}

        allowed_keys = set()
        if not self.add_data:
            allowed_keys.update(simple_filters.keys())
            if self.data_required_columns_keys:
                allowed_keys.update(self.data_required_columns_keys)

        self.allowed_keys = allowed_keys
        self.ref_rank = ref_rank

        # the multi-rank keys are treated separately. They can only appear in the data filters and
        # are not added to the result since they are not associated with a single value (rank)
        self.multi_rank_keys = [f.name for f in self.data_filters.values() if f.column.multi]
        if not self.add_data:
            self.allowed_keys.update(self.multi_rank_keys)

    def extract(self):
        """Generate a result for each subset in the message.

        The keys are iterated in message order and a new subset is detected by the
        appearance of the "subsetNumber" key.

        Yields
        ------
        dict
            The result for a subset. Subsets rejected by the filters are skipped.
        """
        subset_values = dict()
        multi_rank_values = {x: [] for x in self.multi_rank_keys}

        subset = 0
        for key in self.message:
            # only the data section is processed here

            # start new subset
            if key == "subsetNumber":
                if subset >= 1:
                    current_result = self.generate_subset_result(subset, subset_values, multi_rank_values)

                    if current_result:
                        yield current_result

                subset += 1
                subset_values.clear()
                multi_rank_values = {x: [] for x in self.multi_rank_keys}

                for x in self.ref_rank.values():
                    x.reset()

            elif subset >= 1:
                self.process_key(key, subset_values, multi_rank_values)

        # last subset
        current_result = self.generate_subset_result(subset, subset_values, multi_rank_values)
        if current_result:
            yield current_result

    def process_key(self, key, subset_values, multi_rank_values):
        """Collect the value of a single data key into the buffers of the current subset.

        Structural keys (see :obj:`SKIP_KEYS`) are always ignored. When :obj:`add_data`
        is False only the keys needed by the filters and the required columns are kept.

        Parameters
        ----------
        key: str
            The BUFR key to process.
        subset_values: dict
            Buffer of the collected values, keyed by the re-ranked key name. Updated in
            place.
        multi_rank_values: dict
            Buffer of the values of the multi-rank filter keys, keyed by key name.
            Updated in place.
        """
        # print(f" -> processing key: {key}")
        b = UncompressedBufrKey.from_key(key)

        def _get_value(key):
            return convert_missing_scalar(self.message.get(key))

        if b.name in SKIP_KEYS:
            return

        if self.allowed_keys and not (key in self.allowed_keys or b.name in self.allowed_keys):
            return

        v = _get_value(key)
        # self.ref_rank[b.name].set(b.rank)
        # reranked_key = b.rerank(self.ref_rank[b.name].value)

        if b.name in self.ref_rank:
            self.ref_rank[b.name].set(b.rank)
        else:
            self.ref_rank[b.name] = RefRank(b.rank)
        reranked_key = b.rerank(self.ref_rank[b.name].value)
        subset_values[reranked_key] = v

        if b.name in self.multi_rank_keys:
            multi_rank_values[b.name].append(v)

    def generate_subset_result(self, subset, subset_values, multi_rank_values):
        """Apply the filters to the collected values and build the result of a subset.

        Parameters
        ----------
        subset: int
            The 1-based index of the subset. Added to the result as "subsetNumber" when
            :obj:`add_data` is True.
        subset_values: dict
            The values collected for the subset, keyed by the re-ranked key name.
        multi_rank_values: dict
            The values of the multi-rank filter keys collected for the subset, keyed by
            key name.

        Returns
        -------
        dict or None
            The result built from :obj:`base_result` and the collected values, or None
            when the subset does not match the filters.
        """

        def _get_value_subset(key):
            if key in multi_rank_values:
                return multi_rank_values.get(key)
            else:
                return subset_values.get(key)

        current_result = dict(self.base_result)

        # generate result for previous subset
        matched = True
        matched_keys = {}
        for f in self.data_filters.values():
            match, value = f.match_accessor(_get_value_subset)
            if not match:
                matched = False
                break

            if self.add_filters and not f.column.multi:
                matched_keys[f.key] = value

        if matched:
            if not self.add_data and matched_keys:
                for k in matched_keys:
                    subset_values.pop(k, None)

            if self.add_data:
                current_result["subsetNumber"] = subset

            current_result.update(subset_values)

            if current_result:
                # print("yielding:", current_result)
                return dict(current_result)

        return None
